input.onButtonPressed(Button.A, function () {
    CutebotPro.setBlockCnt(28, CutebotProDistanceUnits.Cm)
    CutebotPro.runBlockCnt(3)
    CutebotPro.stopImmediately(CutebotProMotors.M1)
    CutebotPro.setBlockCnt(28, CutebotProDistanceUnits.Cm)
    CutebotPro.runBlockCnt(1)
    CutebotPro.stopImmediately(CutebotProMotors.M1)
    CutebotPro.stopImmediately(CutebotProMotors.M2)
    CutebotPro.setBlockCnt(28, CutebotProDistanceUnits.Cm)
    CutebotPro.runBlockCnt(1)
    CutebotPro.setBlockCnt(28, CutebotProDistanceUnits.Cm)
    CutebotPro.runBlockCnt(1)
    CutebotPro.setBlockCnt(22, CutebotProDistanceUnits.Cm)
    CutebotPro.runBlockCnt(1)
    CutebotPro.setBlockCnt(28, CutebotProDistanceUnits.Cm)
    CutebotPro.runBlockCnt(1)
    CutebotPro.stopImmediately(CutebotProMotors.M1)
    CutebotPro.setBlockCnt(22, CutebotProDistanceUnits.Cm)
    CutebotPro.stopImmediately(CutebotProMotors.M2)
})
CutebotPro.colorLight(CutebotProRGBLight.RGBA, 0xff9da5)
